apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: service-loadbalancer-patch.yaml
  - path: deployment-gke-patch.yaml
images:
  - name: mobile-platform-reliability-api
    newName: GKE_IMAGE_URI_PLACEHOLDER
    newTag: demo
