apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mobile-platform-api
  namespace: mobile-platform-lab
  labels:
    app.kubernetes.io/name: mobile-platform-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: api.local.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mobile-platform-api
                port:
                  name: http
